
import { CityData, PresaleStatus, AirTicketStatus, BuyMethod } from '../types';

const defaultAttendees = (wantGoyang: boolean = false): any[] => [
  { name: 'IVY', wantToGo: wantGoyang, buyMethod: BuyMethod.Daishua, orderedDaishua: false, appliedPresale: false, gotAirTicket: false },
  { name: 'KHT', wantToGo: wantGoyang, buyMethod: BuyMethod.BuySelf, orderedDaishua: false, appliedPresale: false, gotAirTicket: false },
  { name: 'YKT', wantToGo: wantGoyang, buyMethod: BuyMethod.None, orderedDaishua: false, appliedPresale: false, gotAirTicket: false },
];

export const TOUR_LOCATIONS: CityData[] = [
  {
    id: 'goyang-d1',
    city: 'Goyang',
    country: 'South Korea',
    region: 'Asia',
    date: '2026-04-11',
    venueName: 'Goyang Stadium',
    hasAccommodationBooked: true,
    presaleStatus: PresaleStatus.Applied,
    airTicketStatus: AirTicketStatus.Bought,
    recommendedAirports: ['ICN', 'GMP'],
    coordinates: { lat: 37.675, lng: 126.746 },
    status: 'Confirmed',
    attendees: [
      { name: 'IVY', wantToGo: true, buyMethod: BuyMethod.Daishua, orderedDaishua: true, appliedPresale: true, gotAirTicket: true },
      { name: 'KHT', wantToGo: true, buyMethod: BuyMethod.BuySelf, orderedDaishua: false, appliedPresale: true, gotAirTicket: true },
      { name: 'YKT', wantToGo: true, buyMethod: BuyMethod.Daishua, orderedDaishua: true, appliedPresale: true, gotAirTicket: true },
    ]
  },
  {
    id: 'tokyo-d1',
    city: 'Tokyo',
    country: 'Japan',
    region: 'Asia',
    date: '2026-05-15',
    venueName: 'Ajinomoto Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.NotApplied,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['NRT', 'HND'],
    coordinates: { lat: 35.664, lng: 139.527 },
    status: 'Confirmed',
    attendees: [
      { name: 'IVY', wantToGo: true, buyMethod: BuyMethod.Daishua, orderedDaishua: false, appliedPresale: false, gotAirTicket: false },
      { name: 'KHT', wantToGo: true, buyMethod: BuyMethod.BuySelf, orderedDaishua: false, appliedPresale: false, gotAirTicket: false },
      { name: 'YKT', wantToGo: false, buyMethod: BuyMethod.None, orderedDaishua: false, appliedPresale: false, gotAirTicket: false },
    ]
  },
  {
    id: 'london-d1',
    city: 'London',
    country: 'UK',
    region: 'Europe',
    date: '2026-06-20',
    venueName: 'Wembley Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['LHR', 'LGW'],
    coordinates: { lat: 51.556, lng: -0.279 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'paris-d1',
    city: 'Paris',
    country: 'France',
    region: 'Europe',
    date: '2026-06-27',
    venueName: 'Stade de France',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['CDG', 'ORY'],
    coordinates: { lat: 48.924, lng: 2.360 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'stanford-d1',
    city: 'Stanford',
    country: 'USA',
    region: 'North America',
    date: '2026-07-15',
    venueName: 'Stanford Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['SFO', 'SJC'],
    coordinates: { lat: 37.434, lng: -122.161 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'vegas-d1',
    city: 'Vegas',
    country: 'USA',
    region: 'North America',
    date: '2026-07-22',
    venueName: 'Allegiant Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['LAS'],
    coordinates: { lat: 36.090, lng: -115.183 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'kaohsiung-d1',
    city: 'Kaohsiung',
    country: 'Taiwan',
    region: 'Asia',
    date: '2026-09-05',
    venueName: 'National Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['KHH'],
    coordinates: { lat: 22.703, lng: 120.294 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'bangkok-d1',
    city: 'Bangkok',
    country: 'Thailand',
    region: 'Asia',
    date: '2026-09-12',
    venueName: 'Rajamangala Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['BKK', 'DMK'],
    coordinates: { lat: 13.753, lng: 100.622 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'singapore-d1',
    city: 'Singapore',
    country: 'Singapore',
    region: 'Asia',
    date: '2026-09-26',
    venueName: 'National Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['SIN'],
    coordinates: { lat: 1.304, lng: 103.874 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'hongkong-d1',
    city: 'Hong Kong',
    country: 'China',
    region: 'Asia',
    date: '2026-12-05',
    venueName: 'Kai Tak Sports Park',
    hasAccommodationBooked: true,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.Bought,
    recommendedAirports: ['HKG'],
    coordinates: { lat: 22.322, lng: 114.195 },
    status: 'Confirmed',
    attendees: defaultAttendees(true)
  },
  {
    id: 'sydney-tbc',
    city: 'Sydney',
    country: 'Australia',
    region: 'Oceania',
    date: null,
    venueName: 'TBC Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['SYD'],
    coordinates: { lat: -33.868, lng: 151.209 },
    status: 'TBC',
    attendees: defaultAttendees(false)
  },
  {
    id: 'melbourne-tbc',
    city: 'Melbourne',
    country: 'Australia',
    region: 'Oceania',
    date: null,
    venueName: 'TBC Stadium',
    hasAccommodationBooked: false,
    presaleStatus: PresaleStatus.Unknown,
    airTicketStatus: AirTicketStatus.NotBought,
    recommendedAirports: ['MEL'],
    coordinates: { lat: -37.813, lng: 144.963 },
    status: 'TBC',
    attendees: defaultAttendees(false)
  }
];
